import fs from 'node:fs';
const CRLF = String.fromCharCode(13, 10);
const TEST = [
'',
'<script>',
'(async () => {',
'  const out = [];',
'  const log = (ok, name, detail) => out.push((ok ? "PASS" : "FAIL") + " | " + name + " | " + (detail == null ? "" : detail));',
'  const raf = () => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)));',
'  const pre = document.createElement("pre");',
'  pre.id = "nf-appearout";',
'  pre.style.display = "none";',
'  document.body.appendChild(pre);',
'  const done = (t) => { pre.textContent = out.join("\\n"); document.title = t; };',
'  const bgOf = () => getComputedStyle(document.body).backgroundColor;',
'  const lum = (css) => { const m = /rgba?\\(([^)]+)\\)/.exec(String(css)); if (!m) return -1;',
'    const p = m[1].split(",").map(Number); return (0.2126 * p[0] + 0.7152 * p[1] + 0.0722 * p[2]) / 255; };',
'  /* 把截图的「最常见颜色」抠出来：清屏色占了绝大部分像素，所以众数就是清屏色。',
'     JPEG 是有损的，所以只能比「接近」，不能比相等。 */',
'  const shotMode = (url) => new Promise((res) => {',
'    if (typeof url !== "string" || url.indexOf("data:image") !== 0) return res(null);',
'    const im = new Image();',
'    im.onload = () => {',
'      const cv = document.createElement("canvas"); cv.width = im.width; cv.height = im.height;',
'      const g = cv.getContext("2d"); g.drawImage(im, 0, 0);',
'      const d = g.getImageData(0, 0, cv.width, cv.height).data;',
'      const tally = new Map();',
'      for (let i = 0; i < d.length; i += 4 * 13) {',
'        const k = (d[i] << 16) | (d[i + 1] << 8) | d[i + 2];',
'        tally.set(k, (tally.get(k) || 0) + 1);',
'      }',
'      let best = -1, bn = -1;',
'      tally.forEach((v, k) => { if (v > bn) { bn = v; best = k; } });',
'      res({ r: (best >> 16) & 255, g: (best >> 8) & 255, b: best & 255, w: im.width, h: im.height, n: bn });',
'    };',
'    im.onerror = () => res(null);',
'    im.src = url;',
'  });',
'  const hexRgb = (h) => ({ r: parseInt(h.slice(1, 3), 16), g: parseInt(h.slice(3, 5), 16), b: parseInt(h.slice(5, 7), 16) });',
'  try {',
'    await raf();',
'    const NF = window.NF;',
'    if (!NF) throw new Error("NF 未挂载");',
'    if (document.readyState !== "complete") await new Promise(r => addEventListener("load", r));',
'',
'    /* ---------- 1) 主题表 ---------- */',
'    const TH = NF.themes();',
'    log(TH.length === 8, "八套主题都在", TH.map(t => t.id + "=" + t.name).join(" "));',
'    log(NF.appear().themes.join("/") === "deep/midnight/teal/forest/amber/crimson/slate/paper",',
'        "主题 id 顺序稳定（存档里存的就是这个 id）", NF.appear().themes.join("/"));',
'',
'    /* ---------- 2) 一套一套切过去 ---------- */',
'    const seen = [];',
'    let badAttr = "", badBg = 0;',
'    for (let i = 0; i < TH.length; i++) {',
'      NF.setTheme(TH[i].id, false);',
'      await raf();',
'      if (document.documentElement.dataset.theme !== TH[i].id) badAttr += TH[i].id + " ";',
'      if (NF.appear().theme !== TH[i].id) badAttr += TH[i].id + "! ";',
'      const c = bgOf();',
'      if (!/^rgba?\\(/.test(c)) badBg++;',
'      seen.push(c);',
'    }',
'    log(badAttr === "", "切主题后 html[data-theme] 和状态里的 id 都对得上", badAttr || "8/8");',
'    log(badBg === 0, "每套主题下 body 背景都是能解析的颜色", seen[0] + " … " + seen[7]);',
'    log(new Set(seen).size >= 7, "八套主题里至少七套的底色互不相同", new Set(seen).size + " 种：" + Array.from(new Set(seen)).join(" "));',
'    NF.setTheme("paper", false); await raf();',
'    const lPaper = lum(bgOf());',
'    NF.setTheme("deep", false); await raf();',
'    const lDeep = lum(bgOf());',
'    log(lPaper > 0.6 && lDeep < 0.2, "「亮色」真是浅底、「深空蓝」真是深底",',
'        "亮度 paper=" + lPaper.toFixed(2) + " deep=" + lDeep.toFixed(2));',
'    log(NF.setTheme("NoSuchTheme", false).theme === "deep", "不认识的主题名退回深空蓝", NF.appear().theme);',
'    log(NF.appear().theme === "deep" && document.documentElement.dataset.theme === "deep", "退回之后文档属性也跟着退",',
'        document.documentElement.dataset.theme);',
'',
'    /* ---------- 3) 视口背景：状态、清屏色、雾色三边一致 ---------- */',
'    NF.setViewportBg("theme", false); await raf();',
'    const thHex = NF.appear().viewport;',
'    log(/^#[0-9a-f]{6}$/.test(thHex) && NF.appear().vbg === "theme",',
'        "「跟随主题」时视口色取的是主题里的那一格", thHex);',
'    NF.setViewportBg("#123456", false); await raf();',
'    const a3 = NF.appear();',
'    log(a3.viewport === "#123456" && a3.fog === 0x123456 && a3.vbg === "custom",',
'        "自定义视口色：状态、雾色（清屏）两边一起改", a3.viewport + " / 0x" + a3.fog.toString(16) + " / " + a3.vbg);',
'    const before = NF.appear().viewport;',
'    log(NF.setViewportBgHex("not-a-color") === false && NF.appear().viewport === before,',
'        "乱写的颜色被拒掉，视口色不动", "still " + NF.appear().viewport);',
'    NF.setViewportBg("theme", false); await raf();',
'    log(NF.appear().vbg === "theme" && NF.appear().custom === "", "切回「跟随主题」会把自定义色清掉（免得下次偷偷用旧的）",',
'        NF.appear().vbg + " custom=" + JSON.stringify(NF.appear().custom));',
'',
'    /* ---------- 4) 真的画出来了：清屏色 = 截图里最多的那个颜色 ---------- */',
'    for (const pair of [["#101820", "深色"], ["#c8d0d8", "浅色"]]) {',
'      NF.setViewportBg(pair[0], false);',
'      await raf(); await raf();',
'      const mode = await shotMode(NF.shot(320));',
'      const want = hexRgb(pair[0]);',
'      const d = mode ? Math.abs(mode.r - want.r) + Math.abs(mode.g - want.g) + Math.abs(mode.b - want.b) : 999;',
'      log(mode && d <= 24, "视口背景 " + pair[0] + "（" + pair[1] + "）真画到画布上了",',
'          mode ? "截图众数 rgb(" + mode.r + "," + mode.g + "," + mode.b + ") 差 " + d + "，图 " + mode.w + "x" + mode.h : "没截到图");',
'    }',
'',
'    /* ---------- 5) 走界面这条路也要通 ---------- */',
'    const vbgEl = document.getElementById("v-bg");',
'    log(!!vbgEl, "左栏「显示」里的视口取色器在", vbgEl ? vbgEl.type : "没有这个元素");',
'    if (vbgEl) {',
'      vbgEl.value = "#204060";',
'      vbgEl.dispatchEvent(new Event("input", { bubbles: true }));',
'      await raf();',
'      log(NF.appear().viewport === "#204060", "在取色器上挑颜色，视口真的跟着变", NF.appear().viewport);',
'    }',
'    const mAppear = document.getElementById("m-appear");',
'    log(!!mAppear, "顶栏有「外观」菜单", mAppear ? mAppear.textContent.trim().slice(0, 12) : "没有");',
'    const item = document.querySelector("[data-cmd=\\"ap-theme-forest\\"]");',
'    log(!!item, "外观菜单里有「森林绿」这一项", item ? item.textContent.trim() : "没有");',
'    if (item) {',
'      NF.setTheme("deep", false); await raf();',
'      item.click();',
'      await raf();',
'      log(document.documentElement.dataset.theme === "forest" && NF.appear().theme === "forest",',
'          "点菜单项切主题（走的是真人那条路）", document.documentElement.dataset.theme);',
'      const mark = document.getElementById("ap-t-forest");',
'      log(mark && mark.textContent.indexOf("✓") >= 0, "菜单里给当前主题打了勾", mark ? JSON.stringify(mark.textContent) : "没有标记元素");',
'      const markDeep = document.getElementById("ap-t-deep");',
'      log(markDeep && markDeep.textContent.indexOf("✓") < 0, "旧的勾被摘掉了", markDeep ? JSON.stringify(markDeep.textContent) : "没有标记元素");',
'    }',
'',
'    /* ---------- 6) 神经元配色 ---------- */',
'    NF.setTheme("deep", false);',
'    NF.clear();',
'    const ids = [];',
'    for (let i = 0; i < 6; i++) ids.push(NF.addNode(i * 10, 0, 0));',
'    const c0 = ids.map(i => NF.node(i).color);',
'    log(new Set(c0).size === 1, "新建的神经元默认同色（配色不该自己乱跑）", c0[0] + " x6");',
'    const n1 = NF.neuronPalette("warm");',
'    const c1 = ids.map(i => NF.node(i).color);',
'    log(n1 === 6 && new Set(c1).size === 6, "「暖色」整图上色：6 个神经元上了 6 种颜色", n1 + " 个 / " + new Set(c1).size + " 色");',
'    log(c1[0] !== c0[0], "上色前后颜色真的不一样", c0[0] + " → " + c1[0]);',
'    log(NF.neuronPalette("neon") === 6 && NF.neuronPalette("nope") === 0, "不认识的配色名原样退掉（返回 0）", "");',
'    log(NF.neuronPalette("mono") === 6, "「单色」也能上", "");',
'',
'    /* ---------- 7) 换主题不动神经元自己的颜色 ---------- */',
'    const cBefore = ids.map(i => NF.node(i).color).join(",");',
'    NF.setTheme("crimson", false); await raf();',
'    NF.setTheme("paper", false); await raf();',
'    log(ids.map(i => NF.node(i).color).join(",") === cBefore, "换主题不会把神经元颜色洗掉（主题只管界面）", cBefore.slice(0, 40));',
'',
'    /* ---------- 8) 存得住 ---------- */',
'    NF.setTheme("teal", false);',
'    NF.setViewportBg("#0a0a12", false);',
'    NF.setTheme("teal");',
'    let saved = null;',
'    try { saved = JSON.parse(localStorage.getItem("nf.ai") || "null"); } catch (e) { saved = null; }',
'    log(!!saved && saved.appear && saved.appear.theme === "teal" && saved.appear.vbg === "custom" && saved.appear.custom === "#0a0a12",',
'        "主题 / 视口背景写进了本机配置（下次打开还是这套）", saved && saved.appear ? JSON.stringify(saved.appear) : "没写进去");',
'    log(saved && typeof saved.key === "string", "写外观的时候没有把 API Key 弄丢", "key 长度 " + (saved ? String(saved.key || "").length : "?"));',
'',
'    /* ---------- 9) 复位 ---------- */',
'    const rst = document.querySelector("[data-cmd=\\"ap-reset\\"]");',
'    if (rst) { rst.click(); await raf(); }',
'    log(NF.appear().theme === "deep" && NF.appear().vbg === "theme" && NF.appear().custom === "",',
'        "「外观」里的恢复默认把三样都退回去了", JSON.stringify(NF.appear().theme + " / " + NF.appear().vbg));',
'    log(!rst || NF.appear().viewport === NF.appear().viewport.toLowerCase(), "复位后视口色还是合法 hex", NF.appear().viewport);',
'',
'    done("NFAPPEAR " + out.filter(x => x.startsWith("PASS")).length + "P/" + out.filter(x => x.startsWith("FAIL")).length + "F");',
'  } catch (e) {',
'    out.push("FAIL | 抛出异常 | " + String((e && e.stack) || e).slice(0, 400));',
'    done("NFAPPEAR " + out.filter(x => x.startsWith("PASS")).length + "P/" + out.filter(x => x.startsWith("FAIL")).length + "F");',
'  }',
'})();',
'</script>',
''
].join(CRLF);
let html = fs.readFileSync('prototype/神经元编辑器原型.html', 'utf8');
if (!html.includes('</body>')) throw new Error('no body');
html = html.replace('</body>', TEST + '</body>');
fs.writeFileSync('prototype/_appearcheck.html', html, 'utf8');
console.log('generated prototype/_appearcheck.html (' + html.length + ' bytes)');
