/* 生成 prototype/_plastbin.html：可塑性对拍用的三份产物（跑完再执行 py -3 tools/verify_plastic.py 判分）。
   1) 编译一份「学之前」的 .py + model.bin
   2) 用编辑器自己学一步（界面上的模拟激活走的就是这段代码）
   3) 再编译一份「学之后」的 model.bin（里面装的就是编辑器学出来的权重）
   + 编辑器那一拍的 waveOf / val / 每个神经元的档位，交给 python 端做三方对拍。 */
import fs from "node:fs";
const SRC = "prototype/神经元编辑器原型.html";
const html = fs.readFileSync(SRC, "utf8");
if (!html.includes("</body>")) throw new Error("no </body>");
const TEST = [
'<script>',
'(async () => {',
'  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));',
'  const post = (name, body) => fetch("/__dump?name=" + name, { method: "POST", body });',
'  const binU8 = async (b) => (b instanceof Uint8Array) ? b : (b instanceof ArrayBuffer) ? new Uint8Array(b) : new Uint8Array(await b.arrayBuffer());',
'  try {',
'    await sleep(500);',
'    NF.clear();',
'    let seed = 20260920;',
'    const rnd = () => { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return (seed / 0x7fffffff) * 2 - 1; };',
'    const L = [[], [], []];',
'    for (let l = 0; l < 3; l++) for (let i = 0; i < 4; i++) L[l].push(NF.addNode(i * 4, l * 6, 0));',
'    NF.setIO([L[0][0], L[0][1]], "in");',
'    NF.setIO([L[2][3]], "out");',
'    const EIDS = [];',
'    for (let l = 0; l < 2; l++) for (const s of L[l]) for (const d of L[l + 1]) EIDS.push(NF.addEdge(s, d, Math.round((0.35 + Math.abs(rnd()) * 1.1) * 1000) / 1000));',
'    /* 两条跳层边：第二层的神经元会在更早的波次被点亮 —— 拓扑层差跟实际波次差就不是一回事了 */',
'    EIDS.push(NF.addEdge(L[0][0], L[2][0], 0.75));',
'    EIDS.push(NF.addEdge(L[0][1], L[2][1], 0.6));',
'    /* 阈值降到 0、激活改成线性：让信号真能一路传下去。不然 waveOf 全是 -1、',
'       可塑边一条都不会被点亮（第一版就是这么跑出「学了=0」的）。 */',
'    const all = [].concat(L[0], L[1], L[2]);',
'    NF.setThr(all, 0);',
'    for (const i of all) NF.setAct(i, 0);',
'    const p1 = NF.plastAdd({ name: "stdp快", rule: "stdp", lr: 0.25, tau: 2.5, wmin: -2, wmax: 2, decay: 0 });',
'    const p2 = NF.plastAdd({ name: "hebb", rule: "hebb", lr: 0.1, tau: 1, wmin: -1.5, wmax: 1.5, decay: 0 });',
'    const p3 = NF.plastAdd({ name: "衰减", rule: "decay", lr: 0, tau: 1, wmin: -2, wmax: 2, decay: 0.05 });',
'    const p4 = NF.plastAdd({ name: "stdpd", rule: "stdpd", lr: 0.15, tau: 3, wmin: -2, wmax: 2, decay: 0.02 });',
'    NF.setPlast([L[1][0]], p1);',
'    NF.setPlast([L[1][1]], p2);',
'    NF.setPlast([L[1][2]], p3);',
'    NF.setPlast([L[0][2]], p4);',
'    /* 冻结：锁两条可塑边、锁一个挂了档位的神经元（它的出边全被排除）、再锁一个「当可塑边终点」的',
'       神经元。这三条正是编译器排除可塑边的三个条件，同时让冻结清单真的带上下标 ——',
'       bin 里「可塑性表」和「冻结清单」两段偏移写错了不会抛异常，只会静默读错，所以必须一起验。 */',
'    NF.setEdgeLock([EIDS[8], EIDS[16]], 1);',
'    NF.setLock([L[1][1]], 1);',
'    NF.setLock([L[2][1]], 1);',
'    const cc0 = NF.compile("pytorch", { forceBin: true });',
'    if (!cc0.bin) throw new Error("没有 bin: " + JSON.stringify(cc0.errors));',
'    await post("plastbin_net.py", cc0.code);',
'    await post("plastbin_before.bin", await binU8(cc0.bin));',
'    const st0 = NF.plastStats();',
'    const res = NF.plastApply([L[0][0], L[0][1]]);',
'    if (res.error) throw new Error("模拟激活失败: " + res.error);',
'    const cc1 = NF.compile("pytorch", { forceBin: true });',
'    await post("plastbin_after.bin", await binU8(cc1.bin));',
'    const profOf = [];',
'    const lockOfE = []; for (let e = 0; e < cc0.E; e++) lockOfE.push(NF.edge(e).lock ? 1 : 0);',
'    const lockOfN = []; for (let i = 0; i < cc0.N; i++) lockOfN.push(NF.node(i).lock ? 1 : 0);',
'    for (let i = 0; i < cc0.N; i++) profOf.push(NF.plastOf(i).prof);',
'    await post("plastbin_expect.json", JSON.stringify({',
'      N: cc0.N, E: cc0.E, codeLen: cc0.code.length, learned: res.learned,',
'      plastEdges: st0.plasticEdges, profOf: profOf,',
'      edgeLock: lockOfE, nodeLock: lockOfN,',
'      waveOf: Array.from(res.waveOf), val: Array.from(res.val),',
'      profiles: NF.plastProfiles(), rules: NF.plastRules().map((r) => r.id),',
'      warnings: cc0.warnings,',
'    }));',
'    /* ---- 第二张图：多拍（有状态）----',
'       编辑器学一步用的是「第一次点亮的**全局波次**」，多拍时它含「第几拍」的偏移；',
'       编译期只有拓扑层差。这一段只负责证明那个偏移真的会出现。 */',
'    NF.clear();',
'    const m0 = NF.addNode(0, 0, 0), m1 = NF.addNode(6, 0, 0), m2 = NF.addNode(12, 0, 0);',
'    NF.setIO([m0], "in"); NF.setIO([m2], "out");',
'    NF.addEdge(m0, m1, 0.6); NF.addEdge(m1, m2, 1.0);',
'    NF.setAct(m1, 10);           /* 脉冲：攒到 1.0 才发放，所以它会晚好几拍才亮 */',
'    NF.setBias([m1], 0.9);       /* 保持系数 */',
'    NF.setThr([m1], 3); NF.setThr([m2], 0.2);',
'    const pm = NF.plastAdd({ name: "多拍stdp", rule: "stdp", lr: 0.2, tau: 2, wmin: -2, wmax: 2, decay: 0 });',
'    NF.setPlast([m0], pm);',
'    const rsm = NF.plastApply([m0]);',
'    if (rsm.error) throw new Error("多拍模拟失败: " + rsm.error);',
'    const wm = Array.from(rsm.waveOf);',
'    let late = 0; for (const w of wm) if (w >= rsm.span) late++;',
'    await post("plastbin_multi.json", JSON.stringify({ span: rsm.span, steps: rsm.steps, stateful: !!rsm.stateful,',
'      waveOf: wm, late: late, learned: rsm.learned, val: Array.from(rsm.val), activated: rsm.activated, maxWave: rsm.maxWave, order: rsm.order.slice(0, 12) }));',
'    document.title = "NFPLASTBIN OK N=" + cc0.N + " E=" + cc0.E + " 可塑边=" + st0.plasticEdges +',
'      " 学了=" + res.learned + " 多拍点心亮=" + late + " 代码=" + cc0.code.length + "字节";',
'  } catch (e) {',
'    document.title = "NFPLASTBIN ERR " + String((e && e.stack) || e);',
'  }',
'})();',
'<\/script>',
''].join(String.fromCharCode(13, 10));
fs.writeFileSync("prototype/_plastbin.html", html.replace("</body>", TEST + "</body>"));
console.log("generated prototype/_plastbin.html");
