import fs from 'node:fs';
const CRLF = String.fromCharCode(13, 10);
const TEST = [
'',
'<script>',
'(async () => {',
'  const out = [];',
'  const log = (ok, name, detail) => out.push((ok ? "PASS" : "FAIL") + " | " + name + " | " + (detail == null ? "" : detail));',
'  const raf = () => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)));',
'  const pre = document.createElement("pre");',
'  pre.id = "nf-plastout";',
'  pre.style.display = "none";',
'  document.body.appendChild(pre);',
'  const done = (t) => { pre.textContent = out.join("\\n"); document.title = t; };',
'  try {',
'    await raf();',
'    const NF = window.NF;',
'    if (!NF) throw new Error("NF 未挂载");',
'    if (document.readyState !== "complete") await new Promise(r => addEventListener("load", r));',
'',
'    /* ---------- 1) 档位表：默认只有「固定（不学习）」 ---------- */',
'    NF.clear();',
'    log(NF.plastRules().length === 6, "六条学习规则都在", NF.plastRules().map(r => r.id).join("/"));',
'    log(NF.plastProfiles().length === 1 && NF.plastProfiles()[0].rule === "none",',
'        "默认只有一档：固定（不学习）", JSON.stringify(NF.plastProfiles()[0]));',
'',
'    /* ---------- 2) 新建 / 改 / 删档位 ---------- */',
'    const p1 = NF.plastAdd({ name: "STDP 快学", rule: "stdp", lr: 0.2, tau: 5, wmin: -4, wmax: 4, decay: 0 });',
'    log(p1 === 1 && NF.plastProfiles()[1].rule === "stdp" && NF.plastProfiles()[1].lr === 0.2,',
'        "新建一档 STDP：lr=0.2 tau=5", JSON.stringify(NF.plastProfiles()[1]));',
'    NF.plastSet(p1, { lr: 0.3, name: "STDP 更快" });',
'    log(NF.plastProfiles()[1].lr === 0.3 && NF.plastProfiles()[1].name === "STDP 更快", "改档位参数", JSON.stringify(NF.plastProfiles()[1]));',
'    log(NF.plastSet(0, { lr: 0.5 }) === false, "档位 0 改不了（固定不学习永远在）", "");',
'    NF.plastSet(p1, { lr: 0.2 });',
'',
'    /* ---------- 3) 挂到神经元上 + 批量 ---------- */',
'    const a = NF.addNode(0, 0, 0), b = NF.addNode(10, 0, 0), c = NF.addNode(20, 0, 0);',
'    const e0 = NF.addEdge(a, b, 0.5), e1 = NF.addEdge(b, c, 0.5);',
'    NF.setThr([a, b, c], 0.4);',
'    NF.setPlast([a], p1);',
'    log(NF.plastOf(a).prof === p1 && NF.plastOf(a).rule === "stdp", "档位挂到神经元上", JSON.stringify(NF.plastOf(a)));',
'    log(NF.plastStats().byProfile[p1] === 1, "统计里这个档位有 1 个神经元在用", JSON.stringify(NF.plastStats().byProfile));',
'    NF.setPlast([b, c], p1);',
'    log(NF.plastStats().byProfile[p1] === 3, "批量设置：一次给三个神经元挂同一档", JSON.stringify(NF.plastStats().byProfile));',
'    NF.setPlast([b, c], 0);',
'',
'    /* ---------- 4) STDP 一步的数值 ---------- */',
'    const r0 = NF.plastApply([a]);',
'    const w1 = NF.edge(e0).w;',
'    log(Math.abs(w1 - 0.663746178150177) < 1e-6, "STDP 一步：0.5 → 0.5 + 0.2·e^(−1/5)", w1 + "（期望 0.663746178150177）");',
'    log(r0 && r0.activated === 2, "激活按加权和判：a→b 收到 0.5 过阈值、b→c 只收到 0.25 不够 0.4", "activated=" + (r0 && r0.activated));',
'    const r1 = NF.plastApply([a]);',
'    const w2 = NF.edge(e0).w;',
'    log(w2 > w1 && Math.abs(w2 - (w1 + 0.2 * Math.exp(-1 / 5))) < 1e-5, "再学一步继续增强（不是一步到位）", w2);',
'',
'    /* ---------- 5) 冻结的边不学 ---------- */',
'    const w3 = NF.edge(e0).w;',
'    NF.setEdgeLock([e0], true);',
'    NF.plastApply([a]);',
'    log(NF.edge(e0).w === w3, "冻结的边不学", NF.edge(e0).w + " == " + w3);',
'    NF.setEdgeLock([e0], false);',
'',
'    /* ---------- 6) 默认不学：模拟激活不该偷偷改权重 ---------- */',
'    const w4 = NF.edge(e0).w;',
'    NF.plastLearn(false);',
'    NF.simCompute([a]);',
'    log(NF.edge(e0).w === w4, "「学习中」默认关：模拟激活不改权重", NF.edge(e0).w + " == " + w4);',
'    log(NF.plastLearn() === false && NF.plastLearn(true) === true && NF.plastLearn(false) === false, "学习开关能读能写", "");',
'',
'    /* ---------- 7) 强硬抑制 ---------- */',
'    NF.clear();',
'    const n0 = NF.addNode(0, 0, 0), n1 = NF.addNode(10, 0, 0), n2 = NF.addNode(20, 0, 0);',
'    const g0 = NF.addEdge(n0, n1, 0.6), g1 = NF.addEdge(n0, n2, 0.6), g2 = NF.addEdge(n1, n2, 0.6);',
'    NF.setThr([n0, n1, n2], 0.5);',
'    const s1 = NF.simCompute([n0, n1]);',
'    log(s1.activated === 3 && s1.blocked === 0, "没有强硬抑制：喂 0 和 1，三个全亮", "activated=" + s1.activated);',
'    NF.setHard([n1], true);',
'    const s2 = NF.simCompute([n0, n1]);',
'    log(s2.activated === 2 && s2.blocked >= 1, "1 设为强硬抑制：下游 2 这一拍不许激活",',
'        "activated=" + s2.activated + " blocked=" + s2.blocked);',
'    /* 把权重拉到很大也没用：强硬抑制跟权重无关 */',
'    NF.setW(g0, 50); NF.setW(g1, 50); NF.setW(g2, 50);',
'    const s3 = NF.simCompute([n0, n1]);',
'    log(s3.activated === 2, "权重拉到 50 也一样摁住（不是靠负权重）", "activated=" + s3.activated);',
'    NF.setHard([n1], false);',
'    const s4 = NF.simCompute([n0, n1]);',
'    log(s4.activated === 3, "取消强硬抑制以后又亮三个", "activated=" + s4.activated);',
'',
'    /* ---------- 8) 存 / 读：档位表 + 每个神经元的档位号 ---------- */',
'    NF.clear();',
'    const q0 = NF.addNode(0, 0, 0), q1 = NF.addNode(10, 0, 0), q2 = NF.addNode(20, 0, 0);',
'    NF.addEdge(q0, q1, 0.5); NF.addEdge(q1, q2, 0.5);',
'    const p2 = NF.plastAdd({ name: "慢学", rule: "stdpd", lr: 0.03, tau: 9, wmin: -2, wmax: 2, decay: 0.002 });',
'    NF.setPlast([q1], p2);',
'    NF.setHard([q2], true);',
'    const beforeProf = NF.plastProfiles()[p2];',
'    const buf = await NF.encodeV3({});',
'    NF.clear();',
'    log(NF.plastProfiles().length === 1, "新建工程 = 档位表回到只有「固定」", NF.plastProfiles().length + " 档");',
'    await NF.loadBuffer(buf);',
'    const afterProf = NF.plastProfiles()[p2];',
'    log(!!afterProf && afterProf.name === "慢学" && afterProf.rule === "stdpd" && afterProf.decay === beforeProf.decay,',
'        "档位表从工程文件里读回来了", afterProf ? JSON.stringify(afterProf) : "(没有这一档)");',
'    log(NF.plastOf(1).prof === p2 && NF.plastOf(1).rule === "stdpd", "神经元 1 的档位号对上了", JSON.stringify(NF.plastOf(1)));',
'    log(NF.plastOf(2).hard === 1, "神经元 2 的强硬抑制对上了", JSON.stringify(NF.plastOf(2)));',
'    const st2 = NF.plastStats();',
'    log(st2.byProfile[p2] === 1 && st2.hard === 1 && st2.profiles === 2, "统计也一致", JSON.stringify(st2));',
'',
'    /* ---------- 9) 空间分块也带得走（编号会重排，按坐标找人） ---------- */',
'    const buf2 = await NF.encodeV3({ order: "spatial" });',
'    NF.clear();',
'    await NF.loadBuffer(buf2);',
'    let at10 = -1;',
'    for (let i = 0; i < NF.graph().n; i++) { const p = NF.node(i); if (p.x === 10) at10 = i; }',
'    log(at10 >= 0 && NF.plastOf(at10).prof === p2 && NF.plastOf(at10).rule === "stdpd",',
'        "空间 Z 序重排之后档位还跟着它自己的神经元", "神经元在 (" + (at10 >= 0 ? NF.node(at10).x : "?") + ") 档位=" + (at10 >= 0 ? NF.plastOf(at10).prof : "?"));',
'',
'    /* ---------- 10) 删掉一档：用它的退回 0，后面的往前挪 ---------- */',
'    NF.clear();',
'    const y0 = NF.addNode(0, 0, 0), y1 = NF.addNode(10, 0, 0);',
'    const pa = NF.plastAdd({ name: "甲", rule: "hebb", lr: 0.1 });',
'    const pb = NF.plastAdd({ name: "乙", rule: "decay", lr: 0.1, decay: 0.01 });',
'    NF.setPlast([y0], pa); NF.setPlast([y1], pb);',
'    NF.plastDel(pa);',
'    log(NF.plastProfiles().length === 2 && NF.plastProfiles()[1].name === "乙",',
'        "删掉中间那一档之后，后面的档位号整体前移", NF.plastProfiles().map(x => x.name).join("/"));',
'    log(NF.plastOf(y0).prof === 0 && NF.plastStats().byProfile[0] === 1,',
'        "用被删掉那一档的神经元退回「固定（不学习）」", JSON.stringify(NF.plastOf(y0)));',
'    log(NF.plastOf(y1).prof === 1 && NF.plastOf(y1).rule === "decay",',
'        "另一档的神经元跟着前移、规则没串味", JSON.stringify(NF.plastOf(y1)));',
'',
'    /* ---------- 11) 编译产物里真的带上了 ---------- */',
'    NF.clear();',
'    const z0 = NF.addNode(0, 0, 0), z1 = NF.addNode(10, 0, 0), z2 = NF.addNode(20, 0, 0);',
'    NF.addEdge(z0, z1, 0.5); NF.addEdge(z1, z2, 0.5); NF.addEdge(z0, z2, 0.3);',
'    NF.setIO([z0], "in"); NF.setIO([z2], "out");',
'    const pz = NF.plastAdd({ name: "在线学", rule: "stdp", lr: 0.05, tau: 4 });',
'    NF.setPlast([z1], pz);',
'    NF.setHard([z1], true);',
'    const cc = NF.compile("pytorch");',
'    log(cc.code.indexOf("def nf_plastic_step") >= 0 && cc.code.indexOf("plast_ix") >= 0,',
'        "PyTorch 产物里有 nf_plastic_step() 和可塑性表", "代码 " + cc.code.length + " 字符");',
'    log(cc.code.indexOf("hpair_src") >= 0 && cc.code.indexOf("blocked") >= 0,',
'        "前馈网的强硬抑制编进 forward 了", "");',
'    log(cc.code.indexOf("num_hard_pairs") >= 0, "产物里带着压制边的条数", "");',
'    const on = NF.compile("onnx");',
'    log(on.warnings.some(w => w.indexOf("在线学习") >= 0), "ONNX 目标会当场警告「ONNX 表达不了在线学习」",',
'        on.warnings.join(" ¶ ").slice(0, 160));',
'',
'    /* ---------- 12) 状态型 + 可塑性一起用也不炸 ---------- */',
'    NF.clear();',
'    const m0 = NF.addNode(0, 0, 0), m1 = NF.addNode(10, 0, 0);',
'    NF.addEdge(m0, m1, 0.9);',
'    NF.setThr([m0], 0.4);',
'    NF.setAct(m1, 9);      /* 漏电积分 */',
'    const pz2 = NF.plastAdd({ name: "状态网用", rule: "stdp", lr: 0.05, tau: 4 });',
'    NF.setPlast([m0], pz2);',
'    const st3 = NF.plastStats();',
'    log(st3.plasticEdges === 1, "有状态神经元上的入边照样算「可塑边」", "plasticEdges=" + st3.plasticEdges);',
'    const rr = NF.plastApply([m0]);',
'    log(!rr.error, "状态型 + 可塑性一起跑不报错", JSON.stringify(rr.error || "ok"));',
'',
'    done("NFPLAST " + out.filter(x => x.startsWith("PASS")).length + "P/" + out.filter(x => x.startsWith("FAIL")).length + "F");',
'  } catch (e) {',
'    out.push("FAIL | 抛出异常 | " + String((e && e.stack) || e).slice(0, 400));',
'    done("NFPLAST " + out.filter(x => x.startsWith("PASS")).length + "P/" + out.filter(x => x.startsWith("FAIL")).length + "F");',
'  }',
'})();',
'</script>',
''
].join(CRLF);
let html = fs.readFileSync('prototype/神经元编辑器原型.html', 'utf8');
if (!html.includes('</body>')) throw new Error('no body');
html = html.replace('</body>', TEST + '</body>');
fs.writeFileSync('prototype/_plastcheck.html', html, 'utf8');
console.log('generated prototype/_plastcheck.html (' + html.length + ' bytes)');
